# Generated by Django 4.1.7 on 2023-03-26 18:31

from django.db import migrations

def populate_status(apps, schemaeditor):
    status = {
        "published": "A blog post that is visible to everyone.",
        "unpublished": "A blog post that is not visible to everyone.",
    }
    Status = apps.get_model("posts", "Status")
    for key, desc in status.items():
        status_obj = Status(name=key, description=desc)
        status_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_status),
    ]
